# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: College Website

on:
  push:
    branches: [ "college" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Java Maven
      run: |
        java -version
        mvn -version
    - name: Build with Maven
      run: mvn clean install
    - name: Archive artifacts
      uses: actions/upload-artifact@v4
      with:
        name: webapp.war
        path: /home/runner/work/College_Website/College_Website/webapp/target/webapp.war
  Deploy:
    runs-on: new_server
    steps:
      - name: Java Maven
        run: |
          echo "display text of saradhi.txt"
          cat /home/myuser/saradhi.txt
          echo "displayed text of saradhi.txt"
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: webapp.war
          path: ./artifacts
      - name: deploy to prod
        run: |
          echo "display artifacts"
          ls -ltr ./artifacts
          cp -f ./artifacts/webapp.war  /opt/tomcat/apache-tomcat-9.0.89/webapps
          /opt/tomcat/apache-tomcat-9.0.89/bin/shutdown.sh
          sleep 10
          /opt/tomcat/apache-tomcat-9.0.89/bin/shutdown.sh
          echo "completed"
          

